apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-04-02T05:29:08Z"
  labels:
    app: php-test-pod
  name: php-test-pod
spec:
  #initContainers:
  containers:
  - name: db
    image: docker.io/library/mariadb:10.10
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root
    - name: MYSQL_RANDOM_ROOT_PASSWORD
      value: "no"
    - name: MYSQL_PASSWORD
      value: dbpass
    - name: MYSQL_DATABASE
      value: testdb
    - name: MYSQL_ALLOW_EMPTY_PASSWORD
      value: "no"
    - name: MYSQL_USER
      value: dbuser
    ports:
    - containerPort: 3306
      hostPort: 3306
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: volume-db-data-pvc
    args:
    - mysqld
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
  - name: app
    image: app
    volumeMounts:
    - mountPath: /var/www/html
      name: volume-src
    - mountPath: /etc/msmtprc
      name: volume-conf-app-msmtp.msmtprc
    - mountPath: /usr/local/etc/php/conf.d/php_smtp.ini
      name: volume-conf-app-php.smtp.ini
        #containers:
    args:
    - php-fpm
  - name: web
    image: docker.io/library/nginx:stable-alpine
    ports:
    - containerPort: 80
      hostPort: 8080
    volumeMounts:
    - mountPath: /var/www/html
      name: volume-src
    - mountPath: /etc/nginx/nginx.conf
      name: volume-nginx.conf
    - mountPath: /etc/nginx/conf.d/default.conf
      name: volume-nginx.default.conf
    args:
    - nginx
    - -g
    - daemon off;
  - name: smtp
    image: docker.io/jeanberu/mailcatcher:latest
    ports:
    - containerPort: 1025
      hostPort: 1025
    - containerPort: 1080
      hostPort: 1080
    args:
    - --ip
    - 0.0.0.0
  volumes:
  - name: volume-db-data-pvc
    persistentVolumeClaim:
      claimName: php-test-db-data
  - hostPath:
      path: ./src
      type: Directory
    name: volume-src
  - hostPath:
      path: ./app/msmtp.msmtprc
      type: File
    name: volume-conf-app-msmtp.msmtprc
  - hostPath:
      path: ./app/php.smtp.ini
      type: File
    name: volume-conf-app-php.smtp.ini
  - hostPath:
      path: ./web/nginx.conf
      type: File
    name: volume-nginx.conf
  - hostPath:
      path: ./web/nginx.default.conf
      type: File
    name: volume-nginx.default.conf

